# Generated by Django 5.1 on 2024-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False, help_text='Indicates whether the property is rented'),
        ),
    ]
