# Generated by Django 5.1 on 2024-12-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
    ]
